def print1stHeader():
    print()
    print("=========================")
    print(" CryptoSecuritySocialNetwork CLI CLI")
    print(" Project by Alexandre Raccurt - Gabriel Zeizer - Aurélien Santi ")
    print("=========================")
    print()

def printCommandHeader():
    print()
    print("=========================")
    print("AVAILABLE COMMANDS")
    print("=========================")
    print("/help")
    print("/send <text>         - Send text or encoded buffer")
    print("/set <text>          - Set the buffer")
    print("/show                - Show current buffer")
    print("/clear")
    print("/encode shift <key>  - Shift the buffer with the shift <key>")
    print("/encode vigenere <key>  - Vigenere the buffer with the vigenere <key> string")
    print("/encode rsa <n-modular> <e-public key>  - Encode the message with RSA method")
    print("/generate - Generate a private key, a public key and a modular and print it in the console")
    print("/decode rsa <n-modular> <d-private key> [int list from server]  - Decode the encrypted message given by the server")
    #print("/decode vigenere <key>  - Shift the buffer with the shift <key>")
    print("/task shift|vigenere|RSA encode|decode <length>")
    print("/exit")
    print()