def print1stHeader():
    print()
    print("=========================")
    print(" CryptoSecuritySocialNetwork CLI CLI")
    print(" Project by Alexandre Raccurt - Gabriel Zeizer - Aurélien Santi ")
    print("=========================")
    print()

def printCommandHeader():
    print()
    print("=========================")
    print("AVAILABLE COMMANDS")
    print("=========================")
    print("/help")
    print("/send <text>         - Send text or encoded buffer")
    print("/set <text>          - Set the buffer")
    print("/show                - Show current buffer")
    print("/clear")
    print("/encode shift <key>  - Shift the buffer with the shift <key>")
    print("/exit")
    print()